---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  namespace: example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app
rules:
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app
subjects:
  - kind: ServiceAccount
    name: app
    namespace: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: app
      containers:
        - name: app
          image: app
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: debug

