---
apiVersion: v1
kind: Service
metadata:
  name: service02
  namespace: example
  labels:
    ptonini.github.io/ingress-bot: 'true'
  annotations:
    ptonini.github.io/ingress-host: www.example.com
    ptonini.github.io/ingress-path: /path2
spec:
  type: NodePort
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: dummy
